name: Publish Container Image to Github Container Registry
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Chrome
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mosajjal/gorlami:core-latest

      - name: Build Chrome
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/chrome-dockerfile
          push: true
          tags: ghcr.io/mosajjal/gorlami:chrome-latest

      - name: Build Firefox
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/firefox-dockerfile
          push: true
          tags: ghcr.io/mosajjal/gorlami:firefox-latest
      
      - name: Build Kali
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/kali-dockerfile
          push: true
          tags: ghcr.io/mosajjal/gorlami:kali-latest
